name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_job:
    name: Executando job de teste
    runs-on: ubuntu-latest # Altere para 'ubuntu-latest' para evitar problemas com runners específicos
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./github-actions  # Diretório de contexto
        file: ./github-actions/Dockerfile # Caminho para o Dockerfile
        tags: v1
        push: true
